name: Build APK

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y python3-pip git zip unzip openjdk-17-jdk
          pip install buildozer cython

      - name: Init buildozer
        run: |
          buildozer init

      - name: Build APK
        run: |
          buildozer android debug
